Найти коэффициенты

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_percentage_error

In [2]:
df= pd.read_csv("train.csv")
df

index       x_0       x_1       x_2       x_3       x_4       x_5  \
0          0  0.001377 -0.312330  3.830221  0.166320 -1.224697  0.429649   
1          1  0.013704 -0.027573  1.005470  0.210619  0.127280 -0.132307   
2          2  0.052899 -0.187180  2.051134  0.114417  0.087221 -0.114951   
3          3 -0.106739  0.048862  0.606170  0.064275  0.360796  0.030926   
4          4  0.041890  0.121760 -0.684213  0.155978  0.542228 -0.204201   
...      ...       ...       ...       ...       ...       ...       ...   
81681  81681  0.017792 -0.163681  1.584337 -0.146584  0.035550 -0.023723   
81682  81682 -0.066645 -0.179386  1.953583  0.088627  0.249494 -0.578182   
81683  81683 -0.047795 -0.387456  5.210863  0.247560 -0.767073 -0.119413   
81684  81684 -0.045498 -0.320398  3.420069  0.047036 -0.954998 -0.032997   
81685  81685  0.004881 -0.142784  1.517227 -0.028150  0.218005 -0.417164   

            x_6       x_7       x_8  ...      x_46      x_47      x_48  \
0      1.298595  0.075777 -0.305407  ... -3.978286  0.734183 -0.065436   
1      0.339098 -0.055844  0.021325  ...  0.707780  0.010771  0.010401   
2      1.411995 -0.103319 -0.237249  ... -2.085095  0.404859  0.016389   
3     -0.393131  0.016244 -0.017229  ... -0.285642  0.048705 -0.001868   
4     -0.143448 -0.039893  0.134491  ...  2.198981 -0.123793  0.032411   
...         ...       ...       ...  ...       ...       ...       ...   
81681  1.188926 -0.088735 -0.351537  ... -3.079505  0.478363 -0.010010   
81682  1.358388 -0.279439 -0.257999  ... -0.574197  0.450297  0.050664   
81683  2.426770 -0.194622 -0.552561  ... -3.856584  1.184504  0.014722   
81684  1.422030 -0.082255 -0.386574  ... -3.442662  0.806112  0.016144   
81685  0.674261 -0.180381 -0.247947  ... -1.029084  0.394122  0.047664   

           x_49      x_50      x_51      x_52      x_53      x_54     target  
0      0.184826 -6.191027 -1.641520 -0.595980  0.302194 -1.016487  -1.545864  
1     -0.089216 -0.859887 -0.442245 -0.031124  0.028088 -0.146129 -10.972976  
2      0.008621 -2.502265 -0.689139 -0.424500 -0.127823 -0.609472  -1.342009  
3     -0.050163 -0.366623 -0.003307 -0.071816 -0.000375 -0.046915  -1.244498  
4     -0.067868  1.991105  0.455984  0.246094 -0.147255  0.382327   1.686629  
...         ...       ...       ...       ...       ...       ...        ...  
81681 -0.038853 -1.934468 -0.462981 -0.492754 -0.087681 -0.716323  -1.164814  
81682 -0.201040 -1.363513 -0.739452 -0.455479 -0.286012 -0.662417   5.244935  
81683  0.011982 -6.428563 -2.054611 -0.930361 -0.019979 -1.500393   3.107808  
81684  0.095526 -4.804776 -1.488507 -0.683225 -0.017471 -1.086717  15.238161  
81685 -0.242248 -0.698860 -0.313148 -0.426088 -0.285868 -0.558639   0.422315  

[81686 rows x 57 columns]

In [3]:
df = df.drop(columns = 'index')
df

x_0       x_1       x_2       x_3       x_4       x_5       x_6  \
0      0.001377 -0.312330  3.830221  0.166320 -1.224697  0.429649  1.298595   
1      0.013704 -0.027573  1.005470  0.210619  0.127280 -0.132307  0.339098   
2      0.052899 -0.187180  2.051134  0.114417  0.087221 -0.114951  1.411995   
3     -0.106739  0.048862  0.606170  0.064275  0.360796  0.030926 -0.393131   
4      0.041890  0.121760 -0.684213  0.155978  0.542228 -0.204201 -0.143448   
...         ...       ...       ...       ...       ...       ...       ...   
81681  0.017792 -0.163681  1.584337 -0.146584  0.035550 -0.023723  1.188926   
81682 -0.066645 -0.179386  1.953583  0.088627  0.249494 -0.578182  1.358388   
81683 -0.047795 -0.387456  5.210863  0.247560 -0.767073 -0.119413  2.426770   
81684 -0.045498 -0.320398  3.420069  0.047036 -0.954998 -0.032997  1.422030   
81685  0.004881 -0.142784  1.517227 -0.028150  0.218005 -0.417164  0.674261   

            x_7       x_8       x_9  ...      x_46      x_47      x_48  \
0      0.075777 -0.305407 -3.623133  ... -3.978286  0.734183 -0.065436   
1     -0.055844  0.021325  0.199990  ...  0.707780  0.010771  0.010401   
2     -0.103319 -0.237249 -1.126188  ... -2.085095  0.404859  0.016389   
3      0.016244 -0.017229  0.360626  ... -0.285642  0.048705 -0.001868   
4     -0.039893  0.134491  1.511975  ...  2.198981 -0.123793  0.032411   
...         ...       ...       ...  ...       ...       ...       ...   
81681 -0.088735 -0.351537 -1.600475  ... -3.079505  0.478363 -0.010010   
81682 -0.279439 -0.257999 -0.729355  ... -0.574197  0.450297  0.050664   
81683 -0.194622 -0.552561 -3.839824  ... -3.856584  1.184504  0.014722   
81684 -0.082255 -0.386574 -3.081429  ... -3.442662  0.806112  0.016144   
81685 -0.180381 -0.247947  0.489944  ... -1.029084  0.394122  0.047664   

           x_49      x_50      x_51      x_52      x_53      x_54     target  
0      0.184826 -6.191027 -1.641520 -0.595980  0.302194 -1.016487  -1.545864  
1     -0.089216 -0.859887 -0.442245 -0.031124  0.028088 -0.146129 -10.972976  
2      0.008621 -2.502265 -0.689139 -0.424500 -0.127823 -0.609472  -1.342009  
3     -0.050163 -0.366623 -0.003307 -0.071816 -0.000375 -0.046915  -1.244498  
4     -0.067868  1.991105  0.455984  0.246094 -0.147255  0.382327   1.686629  
...         ...       ...       ...       ...       ...       ...        ...  
81681 -0.038853 -1.934468 -0.462981 -0.492754 -0.087681 -0.716323  -1.164814  
81682 -0.201040 -1.363513 -0.739452 -0.455479 -0.286012 -0.662417   5.244935  
81683  0.011982 -6.428563 -2.054611 -0.930361 -0.019979 -1.500393   3.107808  
81684  0.095526 -4.804776 -1.488507 -0.683225 -0.017471 -1.086717  15.238161  
81685 -0.242248 -0.698860 -0.313148 -0.426088 -0.285868 -0.558639   0.422315  

[81686 rows x 56 columns]

In [4]:
Y = np.array(df['target'])
Y

array([ -1.54586367, -10.9729762 ,  -1.34200948, ...,   3.10780755,
        15.23816055,   0.42231537])

In [5]:
X = np.column_stack((df.drop(columns = 'target'), np.ones(len(df)))) #первый столбец из data, второй - единичный вектор длины len(data)
X

array([[ 1.3767311e-03, -3.1233030e-01,  3.8302212e+00, ...,
         3.0219400e-01, -1.0164874e+00,  1.0000000e+00],
       [ 1.3704155e-02, -2.7573105e-02,  1.0054705e+00, ...,
         2.8088417e-02, -1.4612858e-01,  1.0000000e+00],
       [ 5.2899163e-02, -1.8717990e-01,  2.0511340e+00, ...,
        -1.2782271e-01, -6.0947245e-01,  1.0000000e+00],
       ...,
       [-4.7795195e-02, -3.8745597e-01,  5.2108626e+00, ...,
        -1.9978674e-02, -1.5003929e+00,  1.0000000e+00],
       [-4.5498095e-02, -3.2039750e-01,  3.4200690e+00, ...,
        -1.7470634e-02, -1.0867172e+00,  1.0000000e+00],
       [ 4.8813890e-03, -1.4278358e-01,  1.5172273e+00, ...,
        -2.8586770e-01, -5.5863863e-01,  1.0000000e+00]])

МНК

In [6]:
MNK = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(Y)
MNK

array([-9.49887679e+05, -7.56124701e+04,  3.21365998e+05, -2.06698081e+06,
        3.53141559e+03, -1.54138850e+06, -2.45106179e+05, -2.77147564e+05,
       -2.43856337e+06, -4.05847771e+05,  4.83578620e+05,  9.74653116e+05,
        5.43070647e+04,  1.07335551e+06,  1.41459143e+06,  6.02920385e+05,
        2.85306536e+06,  3.53025679e+05,  2.91948821e+06, -1.10471641e+05,
       -1.33039251e+06,  6.86722780e+05,  1.86639942e+06,  2.59874071e+06,
        1.75882817e+05,  3.94672394e+05,  1.43406939e+06, -1.97165584e+06,
        5.85533892e+05,  1.77016964e+05,  1.66481218e+06,  1.43826902e+06,
        5.97281102e+05, -2.60645349e+06, -4.45767627e+05,  3.04086804e+06,
       -5.93436518e+04,  5.40682829e+05,  6.94033030e+05,  2.54718908e+06,
        1.32607050e+05, -9.86624187e+05, -7.00745981e+05, -7.25430784e+05,
       -5.06675552e+04,  1.37421888e+05,  1.86626867e+05, -1.36083088e+06,
       -2.99372356e+06, -1.55711858e+05, -5.66086283e+05,  4.68988941e+05,
        7.91429012e+05, -

In [7]:
y_pred = np.dot(X, MNK)

In [8]:
y_pred

array([ -0.74706219, -13.26811701,   1.82481061, ...,  -0.8364045 ,
         9.82678351,  -4.25210431])

In [12]:
r2_score(Y, y_pred)

0.8901904169511413

In [14]:
 mean_absolute_percentage_error(Y, y_pred)

2.6782971621653715

Градиентный спуск

In [15]:
X = df.drop(columns = 'target') #первый столбец из data, второй - единичный вектор длины len(data)
X

x_0       x_1       x_2       x_3       x_4       x_5       x_6  \
0      0.001377 -0.312330  3.830221  0.166320 -1.224697  0.429649  1.298595   
1      0.013704 -0.027573  1.005470  0.210619  0.127280 -0.132307  0.339098   
2      0.052899 -0.187180  2.051134  0.114417  0.087221 -0.114951  1.411995   
3     -0.106739  0.048862  0.606170  0.064275  0.360796  0.030926 -0.393131   
4      0.041890  0.121760 -0.684213  0.155978  0.542228 -0.204201 -0.143448   
...         ...       ...       ...       ...       ...       ...       ...   
81681  0.017792 -0.163681  1.584337 -0.146584  0.035550 -0.023723  1.188926   
81682 -0.066645 -0.179386  1.953583  0.088627  0.249494 -0.578182  1.358388   
81683 -0.047795 -0.387456  5.210863  0.247560 -0.767073 -0.119413  2.426770   
81684 -0.045498 -0.320398  3.420069  0.047036 -0.954998 -0.032997  1.422030   
81685  0.004881 -0.142784  1.517227 -0.028150  0.218005 -0.417164  0.674261   

            x_7       x_8       x_9  ...      x_45      x_46      x_47  \
0      0.075777 -0.305407 -3.623133  ...  3.064841 -3.978286  0.734183   
1     -0.055844  0.021325  0.199990  ...  0.002108  0.707780  0.010771   
2     -0.103319 -0.237249 -1.126188  ...  0.193937 -2.085095  0.404859   
3      0.016244 -0.017229  0.360626  ...  0.396231 -0.285642  0.048705   
4     -0.039893  0.134491  1.511975  ... -0.945075  2.198981 -0.123793   
...         ...       ...       ...  ...       ...       ...       ...   
81681 -0.088735 -0.351537 -1.600475  ...  0.035464 -3.079505  0.478363   
81682 -0.279439 -0.257999 -0.729355  ... -1.087613 -0.574197  0.450297   
81683 -0.194622 -0.552561 -3.839824  ...  1.808161 -3.856584  1.184504   
81684 -0.082255 -0.386574 -3.081429  ...  1.502859 -3.442662  0.806112   
81685 -0.180381 -0.247947  0.489944  ... -1.329779 -1.029084  0.394122   

           x_48      x_49      x_50      x_51      x_52      x_53      x_54  
0     -0.065436  0.184826 -6.191027 -1.641520 -0.595980  0.302194 -1.016487  
1      0.010401 -0.089216 -0.859887 -0.442245 -0.031124  0.028088 -0.146129  
2      0.016389  0.008621 -2.502265 -0.689139 -0.424500 -0.127823 -0.609472  
3     -0.001868 -0.050163 -0.366623 -0.003307 -0.071816 -0.000375 -0.046915  
4      0.032411 -0.067868  1.991105  0.455984  0.246094 -0.147255  0.382327  
...         ...       ...       ...       ...       ...       ...       ...  
81681 -0.010010 -0.038853 -1.934468 -0.462981 -0.492754 -0.087681 -0.716323  
81682  0.050664 -0.201040 -1.363513 -0.739452 -0.455479 -0.286012 -0.662417  
81683  0.014722  0.011982 -6.428563 -2.054611 -0.930361 -0.019979 -1.500393  
81684  0.016144  0.095526 -4.804776 -1.488507 -0.683225 -0.017471 -1.086717  
81685  0.047664 -0.242248 -0.698860 -0.313148 -0.426088 -0.285868 -0.558639  

[81686 rows x 55 columns]

In [16]:
def add_ones(x):
    return x.insert(0,'x0', np.ones(x.shape[0]))

In [17]:
#thetas - матрица коэффициентов b
def h(x, thetas):
    return np.dot(x, thetas)

In [18]:
def gradient(x, y, thetas, n):
    return np.dot(-x.T, (y - h(x, thetas))) / n

In [19]:
def fit(x, y, iter = 20000, learning_rate = 0.01):
    x, y = x.copy(), y.copy()
    # функцию add_ones() мы объявили выше
    
    add_ones(x)
    
    thetas, n = np.zeros(x.shape[1]), x.shape[0]
    
    for i in range(iter):
        grad = gradient(x, y, thetas, n)
        thetas -= learning_rate * grad
    return thetas

In [20]:
thetas = fit(X, Y, iter = 20000, learning_rate = 0.01)

In [21]:
thetas[0], thetas[1:]

(-1.0841276554096408,
 array([-2.04447702,  1.32269673,  1.26950842, -0.86272228,  8.88800185,
        -3.9882697 , -6.94901153, -0.96727827,  0.57851565, -1.45584629,
         0.3180386 ,  1.3713028 ,  0.32506067,  1.23496366,  0.95649121,
         0.49430536,  0.06014211, -2.54350797, -0.3082365 ,  0.62579321,
         0.68110907, -4.61493796, -1.65917019,  1.16916678,  4.95695559,
        -2.48778742, -3.78725381, -1.69349434,  5.18535874,  2.67800975,
        -0.02075137, -0.71165748,  4.55144155,  1.36783639,  0.62345342,
        -1.18553347, -3.15638167, -0.69356828,  1.54856112, -0.73650203,
         1.1181291 ,  3.40633969, -1.02588328,  2.10376461,  1.00179122,
        -2.05864439,  2.4245191 ,  3.3472499 ,  0.23594452,  1.23278878,
        -1.58321442,  2.58494577,  1.31957653, -0.90769348,  1.44177457]))

In [22]:
def predict(x, thetas):
    x = x.copy()
    add_ones(x)
    return np.dot(x, thetas)

In [23]:
y_pred = predict(X, thetas)

In [25]:
r2_score(Y, y_pred)

0.1808873471285265

In [26]:
 mean_absolute_percentage_error(Y, y_pred)

3.53899260485622

https://www.dmitrymakarov.ru/opt/mlr-04-2/#40-metod-gradientnogo-spuska